#!/bin/sh
#
# Tiny Tazpanel cmdline interface
#

VERSION=1.0

# Get the configuration file and functions
CONFIG="/etc/slitaz/tazpanel.conf"
[ -f $CONFIG ] && . $CONFIG
[ -f tazpanel.conf ] && . tazpanel.conf
[ ! -f $PANEL/lib/libtazpanel ] && \
	echo "No config file or libtazpanel found: $CONFIG" && exit 1
. $PANEL/lib/libtazpanel
. /usr/lib/slitaz/libtaz
source_lib commons

# Include gettext helper script.
. /usr/bin/gettext.sh

# Export package name for gettext.
TEXTDOMAIN='tazpanel'
export TEXTDOMAIN

#
# Commands
#

case "$1" in
	start)
		gettext "Starting TazPanel web server on port $HTTPD_PORT..."
		httpd -p $HTTPD_PORT -u root -c $HTTPD_CONF \
			-r "`gettext \"TazPanel Authentication\"`" &
		status ;;
	stop)
		gettext "Stopping TazPanel web server..."
		killall httpd && status ;;
	passwd|-p)
		echo ""
		gettext "Changing password for TazPanel"
		gettext "New password: " && read pass
		sed -i s"/\/:root:.*/\/:root:$pass/" $HTTPD_CONF
		gettext "Password changed succeffuly"; echo
		echo "" ;;
	*)
		echo ""
		gettext "Usage:" && echo "`basename $0` [start|stop|passwd]"; echo
		echo "" ;;
esac

exit 0
