#!/bin/sh
#
# Tiny Tazpanel cmdline interface
#

CONFIG="/etc/slitaz/tazpanel.conf"

[ -f $CONFIG ] && . $CONFIG
[ -f tazpanel.conf ] && . tazpanel.conf
[ -z $PANEL ] && echo "No config file found" && exit 1

case "$1" in
	start)
		httpd -p $HTTPD_PORT -u root -c $HTTPD_CONF ;;
	stop)
		killall httpd ;;
	passwd|-p)
		echo -e "\nChanging password for TazPanel"
		echo -n "New password: " && read pass
		sed -i s"/\/:root:.*/\/:root:$pass/" $HTTPD_CONF
		echo -e "Password changed succeffuly\n" ;;
	*)
		echo "Usage: `basename $0` [start|stop|passwd]" ;;
esac
